version: '3.4'

services:
  nablaooo:
    image: nablaooo
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 1024:1024
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
