import { proxy } from 'valtio'

export const state = proxy({
    //UI
    works: [],
    sectors: [],
    selectedImg: null,
    loading: false,
    navWidth: 180,
    settWidth: 180,
    portWidth: 0,
    portX: 0,
    containerWidth: 0,
    isPort: false,
    isSett: false,
    themeChanged: false,
    sfxVolume: 1,
    muted: false,
    navPosition: { x: 0, y: 0 },
    prtPosition: { x: 0, y: 0 },
    theme: "light",
    light: {
        panelColor: "#006ebc",
        panelBg: "#ebebeb80",
        textHover: "#F3E8EE",
        sky: "#c3c3c3",
        fog: "#848484",
        link: "#006ebc",
        LiHover: "#006ebc67",
        LiActiveBackground: "#5e5e5e67",
        CD: '#E3B5A4',
        CDHover: '#0A0A0A',
        CDRough: 0,
        Surface: '#AEDEFF',
        spotIntensity: 6,
        ambIntensity: 0.1,
        rectIntensity: 5,

    },
    dark: {
        panelColor: "#006ebc",
        panelBg: "#64646460",
        textHover: "#F3E8EE",
        sky: "#1F1F1F",
        fog: "#030303",
        link: "#C6182A",
        LiHover: "#006ebc67",
        LiActiveBackground: "#ebebeb67",
        CD: "#0A0A0A",
        CDHover: '#E3B5A4',
        CDRough: 9,
        Surface: '#47b3ff',
        spotlight: '#646464',
        spotIntensity: 8,
        ambIntensity: 1,
        rectIntensity: 5,
    },
    //Canvas
    paused: false,
    userControlled: true,
    canvasVisible: true,
    CDRotationY: 0.002,
    CDRotationZ: 0.0001,
    cameraPosition: [20, 15, 0],
    modalPosition: { x: 0, y: 0 },
    autoRotateSpeed: 0.09,
});