import { proxy } from 'valtio'

export const state = proxy({
    //UI
    works: [],
    sectors: [],
    selectedImg: null,
    loading: false,
    navWidth: 180,
    settWidth: 180,
    portWidth: 0,
    portX: 0,
    containerWidth: 0,
    isPort: false,
    isSett: false,
    themeChanged: false,
    sfxVolume: 1,
    muted: false,
    navPosition: { x: 0, y: 0 },
    prtPosition: { x: 0, y: 0 },
    //Search
    query: null,
    //Theme
    theme: "light",
    light: {
        panelColor: "#006ebc",
        panelBg: "#ebebeb80",
        textHover: "#F3E8EE",
        placeholder: "#006ebc",
        sky: "#c3c3c3",
        fog: "#848484",
        link: "#006ebc",
        LiHover: "#006ebc67",
        LiActiveBackground: "#5e5e5e67",
        CD: '#E3B5A4',
        CDHover: '#0A0A0A',
        CDRough: 0,
        Surface: '#AEDEFF',
        SurfaceRough: '0',
        spotIntensity: 6,
        ambIntensity: 0.1,
        rectIntensity: 5,
        blend: "color-burn",
        sectorColor: "#0074B0",
        searchFocus: "0 0 50px 50px",
        backdrop: "rgba(255, 255, 255, 0.50)",
    },
    dark: {
        panelColor: "#00DCFF",
        panelBg: "#64646460",
        textHover: "#F3E8EE",
        placeholder: "unset",
        sky: "#1F1F1F",
        fog: "#030303",
        link: "#C6182A",
        LiHover: "#00DCFF67",
        LiActiveBackground: "#ebebeb67",
        CD: "#070707",
        CDHover: '#E3B5A4',
        CDRough: 9,
        Surface: '#00DCFF',
        SurfaceRough: '1',
        spotlight: '#646464',
        spotIntensity: 0,
        ambIntensity: 1,
        rectIntensity: 5,
        blend: "difference",
        sectorColor: "#00DCFF",
        searchFocus: "0 0 0px 0px",
        backdrop: "rgba(0, 0, 0, 0.50)",
    },
    //Canvas
    paused: false,
    userControlled: true,
    canvasVisible: true,
    CDRotationY: 0.002,
    CDRotationZ: 0.0001,
    cameraPosition: [20, 0, 0],
    modalPosition: { x: 0, y: 0 },
    autoRotateSpeed: 0.09,
});